var constants = {
    //// List
    SR: 'SR#',
    CLEAR: 'Clear',
    FILTER: 'Filter',
    STATUS: 'Status',
    PERSON: 'Person',
    PHONE_HEADER: 'Phone',
    NUMBER_HEADER: 'Number',
    POSITION: 'Position',
    NAME: 'Name',
    EMAIL: 'Email',
    SCHEDULEDATE: 'Schedule Date',
    EXPERIENCE_HEADER: 'Exp.',
    YEARS_HEADER: 'Yrs.',
    EXPERIENCE_YEARS_HEADER: 'Exp. Yrs.',
    SCHEDULE_HEADER: 'Schedule',
    DATE_HEADER: 'Date',
    TIME_HEADER: 'Time',

    //// Forms
    SAVE: 'Save',
    EDIT: 'Edit',
    UPDATE: 'Update',
    DELETE: 'Delete',
    SUBMIT: 'Submit',
    CANCEL: 'Cancel',
    REQUIRED_MESSAGE: 'Please enter',
    VALIDITY_MESSAGE: 'Please enter valid',
    SELECT_MESSAGE: 'Please select',
    SORTORDER_MESSAGE: 'Please enter Sort Order between 1 to 9999',
    ALTERNATENUMBER_MESSAGE: 'Please enter another phone number',
    DROPDOWN_PLACEHOLDER: 'Select an option',
    REQUIRED_FILE_MESSAGE: 'Please select file',
    TXT_OLDPASSWORD: 'oldpassword',
    TXT_PASSWORD: 'password',
    TXT_CONFIRMPASSWORD: 'confirmPassword',
    LBL_OLDPASSWORD: 'oldpasswordLabel',
    LBL_OLDPASSWORD_ERROR: 'oldpasswordError',
    LBL_PASSWORD: 'lblPassword',
    PASSWORDLABEL: 'passwordLabel',
    LBL_PASSWORD_ERROR: 'passwordError',
    LBL_CONFIRM_PASSWORD: 'lblcnfPassword',
    LBL_CONFIRM_PASSWORD_LABEL: 'confirmPasswordLabel',
    LBL_CONFIRMPASSWORD_ERROR: 'confirmPasswordError',
    INPUT_PASSWORD: 'inputPassword',
    INPUT_CONFIRMPASSWORD: 'inputcnfPassword',
    LBL_FORGOTPASSWORDFORM: 'forgotPasswordForm',
    EMAILLABEL: 'EmailLabel',
    EMAILERROR: 'EmailError',
    PASSWORD_LABEL: 'PasswordLabel',
    LBL_PASSWORDERROR: 'PasswordError',
    LBL_RESUME: 'ResumeLabel',
    DIV_FORM: 'divForm',
    DIV_BUTTON: 'divButton',
    CONFLICT: 'conflict',
    LBL_CONFLICT: 'Conflict',
    LBL_TOTAL: 'Total',

    //// Common
    LBL_STARTWAITING: 'startWaiting',
    LBL_STOPWAITING: 'stopWaiting',
    REQUEST_LOGOFF_USER: 'REQUEST_LOGOFF_USER',
    ADD_NEW_INTERVIEWSCHEDULE: 'ADD_NEW_INTERVIEWSCHEDULE',
    GET_ALL_INTERVIEWS: 'GET_ALL_INTERVIEWS',
    GET_MONTHLYINTERVIEWS: 'GET_MONTHLYINTERVIEWS',
    GET_INTERVIEW_BY_ID: 'GET_INTERVIEW_BY_ID',
    GET_RESULT_BY_ID: 'GET_RESULT_BY_ID',
    UPDATE_INTERVIEWSCHEDULE: 'UPDATE_INTERVIEWSCHEDULE',
    DELETE_INTERVIEWSCHEDULE: 'DELETE_INTERVIEWSCHEDULE',
    DELETE_MULTIPLE_INTERVIEWSCHEDULE: 'DELETE_MULTIPLE_INTERVIEWSCHEDULE',
    GET_ALL_INTERVIEWRESULT: 'GET_ALL_INTERVIEWRESULT',
    GET_ALL_INTERVIEWSTATUS: 'GET_ALL_INTERVIEWSTATUS',
    NEW_QUESTIONS: 'NEW_QUESTIONS',
    ANSWER_FIND_BY_ID: 'ANSWER_FIND_BY_ID',
    GET_ALL_ANSWER: 'GET_ALL_ANSWER',
    GET_ALL_QUESTIONS: 'GET_ALL_QUESTIONS',
    ADD_NEW_QUESTIONCATEGORY: 'ADD_NEW_QUESTIONCATEGORY',
    GET_ALL_QUESTIONCATEGORIES: 'GET_ALL_QUESTIONCATEGORIES',
    GET_ACTIVE_QUESTIONCATEGORIES: 'GET_ACTIVE_QUESTIONCATEGORIES',
    GET_QUESTIONCATEGORY_BY_ID: 'GET_QUESTIONCATEGORY_BY_ID',
    UPDATE_QUESTIONCATEGORY: 'UPDATE_QUESTIONCATEGORY',
    DELETE_QUESTIONCATEGORY: 'DELETE_QUESTIONCATEGORY',
    REQUEST_LOGIN_USER_SUCCESS: 'REQUEST_LOGIN_USER_SUCCESS',
    REQUEST_LOGIN_USER_ERROR: 'REQUEST_LOGIN_USER_ERROR',
    REQUEST_CHANGEPASSWORD_SUCCESS: 'REQUEST_CHANGEPASSWORD_SUCCESS',
    REQUEST_CHANGEPASSWORD_ERROR: 'REQUEST_CHANGEPASSWORD_ERROR',
    REQUEST_FORGOTPASSWORD_SUCCESS: 'REQUEST_FORGOTPASSWORD_SUCCESS',
    REQUEST_FORGOTPASSWORD_ERROR: 'REQUEST_FORGOTPASSWORD_ERROR',
    ADD_NEW_USER: 'ADD_NEW_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_USER_BY_ID: 'GET_USER_BY_ID',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    SEND_MAIL: 'SEND_MAIL',
    LBL_OK_RESPONSE: 'OK',
    LBL_OK: 'Ok',
    FORGOTPASSWORD_FROM: 'Hetal Mehta <test.ansibytecode@gmail.com>',
    MAIL_SUBJECT: 'Evaluation of the Interview',
    SEND_MAIL_SUCCESS: 'SendMailUnsuccess',
    LBL_NEW: 'new',
    LBL_ONE: '1',
    LBL_TRUE: 'true',
    LBL_FALSE: 'false',
    LBL_ACTIVE: 'Active',
    LBL_INACTIVE: 'inactive',
    LBL_NO: 'No',
    LBL_LEAD: 'lead',
    LBL_INTERVIWEES: 'Interviewees',
    LBL_QUESTIONCATEGORIES:'Question Categories',
    LBL_REPORTS: 'Reports',
    LBL_MONTHLYINTERVIEWS: 'Monthly Interviews',
    LBL_PERSONWISEINTERVIEWS: 'Person Wise Interviews',
    LBL_LOGOUT: 'Logout',

    //// Authorization
    SIGNIN_HEADER: 'Sign in to RMS',
    SIGNUP_HEADER: 'Sign up to RMS',
    CHANGEPASSWORD: 'Change Password',
    OLDPASSWORD: 'Old Password',
    NEWPASSWORD: 'New Password',
    CONFIRMPASSWORD: 'Confirm Password',
    FORGOTPASSWORD: 'Forgot Password',
    PASSWORD: 'Password',
    LOGIN: 'Login',
    REQUIRED_OLDPWD_MESSAGE: 'Please enter correct old password',
    MATCH_PASSWORD_MESSAGE: 'Password and Confirm Password does not match',
    PWD_LENGTH_MESSAGE: 'Password must be at least 8 characters long',
    PWD_SEND_MESSAGE: 'New Password has been sent to your mail account',
    USER_STATUS_MESSAGE: 'User is inactive or removed',
    INVALID_EMAIL_MESSAGE: 'Invalid email or password',

    //// User
    USER: 'User',
    USERS: 'Users',
    NEWUSER: 'New User',
    USER_LIST: 'User List',
    EMAIL_EXIST_MESSAGE: 'Email id already exist',
    REGISTERUSER_SUCCESS_MESSAGE: 'User successfully registered',
    LBL_CONTACTNUMBER: 'ContactNumberLabel',
    TXT_CONTACTNUMBER: 'ContactNumber',
    LBL_CONTACTNUMBER_ERROR: 'ContactNumberError',
    CONFIRM_PASSWORDLABEL: 'ConfirmPasswordLabel',
    TEXTBOX_CONFIRMPASSWORD: 'ConfirmPassword',
    LBL_CONFIRM_PASSWORD_ERROR: 'ConfirmPasswordError',
    CONFIRM_PASSWORD: 'Confirmpassword',
    CONFIRM_PASSWORD_LABEL: 'ConfirmpasswordLabel',
    CONFIRM_PASSWORD_ERROR: 'ConfirmpasswordError',
    REGISTER_FORM: 'registerForm',

    //// Interview
    INTERVIEW: 'Interview',
    INTERVIEWS: 'Interviews',
    NEWINTERVIEWEE: 'New Interviewee',
    NEWINTERVIEW: 'New Interview',
    INTERVIEWEE_LIST: 'Interviewee List',
    INTERVIEW_EXIST: 'Interview already scheduled',
    FIRSTNAME: 'First Name',
    LASTNAME: 'Last Name',
    PHONENUMBER: 'Phone Number',
    ALTERNATENUMBER: 'Alternate Number',
    SCHEDULETIME: 'Schedule Time',
    EXPERIENCE_YEARS: 'Experience (Years)',
    INTERVIEWMODE: 'Interview Mode',
    INTERVIEWSTATUS: 'Interview Status',
    TOEMAIL: 'To Email',
    CCEMAIL: 'CC Email',
    RESUME: 'Resume',
    UPLOADFILE: 'Upload File',
    REMOVERESUME: 'Remove Resume',
    SEND_EMAIL: 'Send Email',
    SEND_EMAILS: 'Send Emails',
    SYNC_QUESTIONS: 'Sync Questions',
    REPORTSHARED: 'Report Shared',
    CONTACTNUMBER: 'Contact Number',
    ISARCHIVED : 'Archived',
    ISINVOICED : 'Invoiced',
    LBL_FIRSTNAME: 'FirstNameLabel',
    TXT_FIRSTNAME: 'FirstName',
    LBL_FIRSTNAME_ERROR: 'FirstNameError',
    LBL_LASTNAME: 'LastNameLabel',
    TXT_LASTNAME: 'LastName',
    LBL_LASTNAME_ERROR: 'LastNameError',
    LBL_PHONENUMBER: 'PhoneNumberLabel',
    TXT_PHONENUMBER: 'PhoneNumber',
    LBL_PHONENUMBER_ERROR: 'PhoneNumberError',
    LBL_ALTERNATENUMBER: 'AlternatePhoneNumberLabel',
    TXT_ALTERNATENUMBER: 'AlternatePhoneNumber',
    LBL_ALTERNATENUMBER_ERROR: 'AlternatePhoneNumberError',
    LBL_EMAILID: 'EmailIdLabel',
    TXT_EMAILID: 'EmailId',
    LBL_EMAILID_ERROR: 'EmailIdError',
    LBL_SCHEDULEDATE: 'scheduleDateLabel',
    TXT_SCHEDULEDATE: 'scheduleDate',
    LBL_SCHEDULEDATE_ERROR: 'scheduleDateError',
    LBL_SCHEDULETIME: 'ScheduleTimeLabel',
    TXT_SCHEDULETIME: 'ScheduleTime',
    LBL_SCHEDULETIME_ERROR: 'ScheduleTimeError',
    LBL_POSITIONNAME: 'PositionNameLabel',
    TXT_POSITIONNAME: 'PositionName',
    LBL_POSITIONNAME_ERROR: 'PositionNameError',
    LBL_EXPERIENCE: 'ExperienceLabel',
    TXT_EXPERIENCE: 'Experience',
    LBL_EXPERIENCE_ERROR: 'ExperienceError',
    LBL_MODEOFINTERVIEW: 'ModeofInterviewLabel',
    TXT_MODEOFINTERVIEW: 'ModeofInterview',
    LBL_MODEOFINTERVIEW_ERROR: 'ModeofInterviewError',
    LBL_INTERVIEWSTATUS: 'ddlInterviewStatusLabel',
    DDL_INTERVIEWSTATUS: 'ddlInterviewStatus',
    LBL_INTERVIEWSTATUS_ERROR: 'ddlInterviewStatusError',
    LBL_TOEMAIL: 'ddlToEmailLabel',
    DDL_TOEMAIL: 'ddlToEmail',
    LBL_TOEMAIL_ERROR: 'ddlToEmailError',
    LBL_RESUME_ERROR: 'ResumeError',

    //// Question Category
    QUESTIONCATEGORY:'Question Category',
    QUESTIONCATEGORY_EXIST: 'Question Category already exist',
    CATEGORIES: 'Categories',
    QUESTIONCATEGORY_LIST: 'Question Category List',
    NEW_QUESTIONCATEGORY: 'New Question Category',
    DISPLAYNAME: 'Display Name',
    LBL_QUESTIONCATEGORYNAME: 'QuestionCategoryNameLabel',
    TXT_QUESTIONCATEGORYNAME: 'QuestionCategoryName',
    LBL_QUESTIONCATEGORYNAME_ERROR: 'QuestionCategoryNameError',
    LBL_DISPLAYNAME: 'DisplayNameLabel',
    TXT_DISPLAYNAME: 'DisplayName',
    LBL_DISPLAYNAME_ERROR: 'DisplayNameError',
    LBL_SORTORDER: 'SortOrderLabel',
    TXT_SORTORDER: 'SortOrder',
    LBL_SORTORDER_ERROR: 'SortOrderError',

    //// Question
    QUESTION: 'Question',
    QUESTIONS: 'Questions',
    QUESTION_LIST: 'Question List',
    NEW_QUESTION: 'New Question',
    SORTORDER: 'Sort Order',
    QUESTION_EXIST: 'Question already exist',
    AVERAGE: 'Average',
    BELOW_AVERAGE: 'Below Avg.',
    GOOD: 'Good',
    EXCELLENT: 'Excellent',
    NONE: 'N.A',
    REMARKS: 'Remarks',
    ANSWER: 'Answer',
    SCORE: 'Score',
    RATING:'Rating',
    SCORE_MESSAGE: 'Please enter score between 1 to 10',
    QUESTIONLIST_UPDATE_SUCCESS_MESSAGE: 'Question list has been updated successfully',
    SAVE_DETAILS_FOR_SEND_EMAIL: 'Please save the details',
    LBL_DDLQUESTIONCATEGORY: 'ddlQuestionCategoryLabel',
    DDL_QUESTIONCATEGORY: 'ddlQuestionCategory',
    LBL_DDLQUESTIONCATEGORY_ERROR: 'ddlQuestionCategoryError',
    LBL_QUESTION: 'QuestionLabel',
    LBL_QUESTION_ERROR: 'QuestionError',
    BTN_SYNCQUESTIONS: 'syncQuestions',
    BTN_SENDMAIL: 'sendMail',
    LBL_INTERVIEWSCORE: 'interviewScoreLabel',
    TXT_INTERVIEWSCORE: 'interviewScore',
    LBL_INTERVIEWSCORE_ERROR: 'interviewScoreError',
    LBL_INTERVIEWRESULT: 'InterviewResultLabel',
    DDL_INTERVIEWRESULT: 'ddlInterviewResult',
    LBL_INTERVIEWRESULT_ERROR: 'InterviewResultError',
    LBL_RECOMMENDATIONS: 'RecommendationsLabel',
    TXT_RECOMMENDATIONS: 'Recommendations',
    LBL_RECOMMENDATIONS_ERROR: 'RecommendationsError',

    //// Messages
    INSERT_SUCCESS_MESSAGE : 'Record has been saved successfully',
    UPDATE_SUCCESS_MESSAGE : 'Record has been updated successfully',
    DELETE_SUCCESS_MESSAGE: 'Record has been deleted successfully',
    MULTIPLE_DELETE_SUCCESS_MESSAGE: 'Records have been deleted successfully',
    FILE_UPLOAD_MESSAGE: 'File has been uploaded successfully',
    FILE_REMOVE_MESSAGE: 'File has been removed successfully',
    RECORD_ALREADY_EXISTS : '',
    DELETE_CONFIRMATION: 'Are you sure want to delete?',
    REFERENCE_EXIST_MESSAGE: "The selected record is referred in the application, can't complete delete operation",

    //// Email Messages
    SINGLE_MESSAGE_SENT_SUCCESSFUL : 'Email has been sent successfully',
    MULTIPLE_MESSAGE_SENT_SUCCESSFUL : 'Emails have been sent successfully',
    MESSAGE_SENT_UNSUCCESSFUL :'',
    INTERVIEW_SELECTION : 'Please select Interviewee',

    //// Reports
    SEARCH: 'Search',
    COUNT: 'Count',
    SELECTOPTION_MESSAGE: 'Please select at least one option',
    FROMDATE_MESSAGE: 'Please select From Date',
    TODATE_MESSAGE: 'Please select To Date',
    DATEDIFF_MESSAGE: 'From Date should be less than To Date',
    FROMDATE: 'From Date',
    TODATE: 'To Date',
    INTERVIEWREPORT: 'Interview Report',
    PERSONWISEREPORT: 'Person Wise Report',
    SELECTPERSON_MESSAGE: 'Please select more persons',
    RESULT: 'Result',
    MONTHLYREPORT: 'Monthly Report',
    MONTH: 'Month',
    YEAR: 'Year',
    DDL_PERSON: 'ddlPerson',
    BTN_CLEAR: 'btnClear',
    DDL_MONTHLABEL: 'ddlMonthLabel',
    DDL_MONTH: 'ddlMonth',
    LBL_MONTH_ERROR: 'ddlMonthError',
    DDL_YEARLABEL: 'ddlYearLabel',
    DDL_YEAR: 'ddlYear',
    LBL_YEAR_ERROR: 'ddlYearError',
};

module.exports = constants;
